# Generated by Django 4.2.7 on 2026-05-10 19:10

import django.core.validators
from django.db import migrations, models
import pdf_analysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_analysis', '0002_pdfanalysisresult_complexity_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to=pdf_analysis.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
